services:
  # Backend Spring Boot Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lifelynk-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - hospital_network

  # Frontend React Application
  frontend:
    build:
      context: ./lifelynk-frontend
      dockerfile: Dockerfile
    container_name: lifelynk-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge